### ISSUE TITLE
Turn it of for certain contend dimensions

### ISSUE THREAD

**Issue by jonnitto** [mocdk/MOC.SynchronizeUrl#1]
If you have a site in chinese, you get in trouble with this great plugin. It should be possible to turn it off for certain dimensions...

**Comment by aertmann** [comment]
@jonnitto: How so? What happens? Technically there shouldn't be any difference between languages..

**Comment by jonnitto** [comment]
It writes the path with chinese symbols and the pages weren't accessible anymore. Happend on http://www.rondo-online.com/cn

**Comment by aertmann** [comment]
Hi again,

Okay now I see. It's not really the fault of this package, rather it's a general problem in Neos. Creating pages using non-latin characters leads to all kinds of problems. I guess you have a workflow that works around the problem, since the pages are created in english first and then translated to Chinese.

In that case I see it could be useful to disable the functionality in a specific language dimension. A pull request for such functionality would be welcome, however I feel it's more an underlying problem.

I spend some time fixing said problem in the core, https://github.com/neos/neos-development-collection/pull/394. However that will mean that when the titles are changed from English to Chinese, the url would change to a transliterated path instead of keeping the English one. Which could be preferred in some cases, hence I'd accept the suggested feature.

If you want to fund the development of it I'd be happy to develop it for you, just get in touch and we'll find a solution.

Cheers,
Aske

**Comment by jonnitto** [comment]
With the newer version of neos, the underlying problem is solved. Now it works like a charm!
